repos:
#
# formatters:
#
  - repo: https://github.com/johann-petrak/licenseheaders
    rev: v0.8.8
    hooks:
      - id: licenseheaders
        args: ['-t', '.mit-license.tmpl', '-E', '.py', '-f']
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.16.7
    hooks:
      - id: ruff-check
        args: [--fix]
      - id: ruff-format
  - repo: https://github.com/DanielNoord/pydocstringformatter
    rev: v0.7.3
    hooks:
      - id: pydocstringformatter
#
# linters
#
  - repo: local
    hooks:
      - id: mypy
        name: mypy
        entry: mypy
        language: system
        types: [python]
        pass_filenames: false
        require_serial: true
      - id: pyright
        name: pyright
        entry: pyright
        language: system
        types: [python]
        pass_filenames: false
        require_serial: true
