name: Markdown Link Check

on:
  workflow_dispatch:
    inputs:
      tags:
        description: Manual Markdown Link Check run
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  merge_group:
    types: [checks_requested]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-${{ github.event_name }}
  cancel-in-progress: true

jobs:
  # Check in-repo markdown links
  markdown-link-check:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    timeout-minutes: 5
    steps:
    - uses: actions/checkout@v4
    - uses: gaurav-nelson/github-action-markdown-link-check@v1
      with:
        use-quiet-mode: yes
        use-verbose-mode: yes
        folder-path: './examples, ./src, ./tests'
        file-path: './CODE_OF_CONDUCT.md, ./CONTRIBUTING.md, ./README.md, ./SECURITY.md, ./SUPPORT.md'
        config-file: './.github/workflows/markdown-link-check-config.json'
